services:
  backend:
    image: simincao/iiasa-interview-backend:latest
    container_name: iiasa_interview_fastapi_backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: simincao/iiasa-interview-frontend:latest
    container_name: iiasa_interview_react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always