[map_settings]

zoom_levels = "2-4"
map_dir= "data/maps"
api_prefix= "/maps"
container_name= ""
blob_account_url= ""
blob_sas_token= ""

[csv_settings]

csv_dir= "data/csvs"
api_prefix= "/csvs"
container_name= ""
blob_account_url= ""
blob_sas_token= ""

[app_settings]

title= "Data Visualiser Backend"
version= "0.1.0"
api_prefix= "/api"

[auth_settings]

api_prefix= "/login"